export const themes = {
    blue: {
        bg: 'bg-slate-950',
        card: 'bg-slate-900',
        border: 'border-slate-800',
        text: 'text-slate-50',
        textSecondary: 'text-slate-200',
        textMuted: 'text-slate-500',
        accent: 'text-blue-400',
        accentHover: 'hover:text-blue-300',
        button: 'bg-slate-800 hover:bg-slate-700',
        buttonIcon: 'text-blue-400',
        primary: 'bg-blue-700 hover:bg-blue-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-slate-800',
        progressFill: 'bg-blue-600',
        progressGlow: 'shadow-blue-900/50',
        arrow: 'border-t-blue-500',
    },
    purple: {
        bg: 'bg-slate-950',
        card: 'bg-slate-900',
        border: 'border-slate-800',
        text: 'text-slate-50',
        textSecondary: 'text-slate-200',
        textMuted: 'text-slate-500',
        accent: 'text-purple-400',
        accentHover: 'hover:text-purple-300',
        button: 'bg-slate-800 hover:bg-slate-700',
        buttonIcon: 'text-purple-400',
        primary: 'bg-purple-700 hover:bg-purple-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-slate-800',
        progressFill: 'bg-purple-600',
        progressGlow: 'shadow-purple-900/50',
        arrow: 'border-t-purple-500',
    },
    green: {
        bg: 'bg-slate-950',
        card: 'bg-slate-900',
        border: 'border-slate-800',
        text: 'text-slate-50',
        textSecondary: 'text-slate-200',
        textMuted: 'text-slate-500',
        accent: 'text-emerald-400',
        accentHover: 'hover:text-emerald-300',
        button: 'bg-slate-800 hover:bg-slate-700',
        buttonIcon: 'text-emerald-400',
        primary: 'bg-emerald-700 hover:bg-emerald-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-slate-800',
        progressFill: 'bg-emerald-600',
        progressGlow: 'shadow-emerald-900/50',
        arrow: 'border-t-emerald-500',
    },
    orange: {
        bg: 'bg-slate-950',
        card: 'bg-slate-900',
        border: 'border-slate-800',
        text: 'text-slate-50',
        textSecondary: 'text-slate-200',
        textMuted: 'text-slate-500',
        accent: 'text-orange-400',
        accentHover: 'hover:text-orange-300',
        button: 'bg-slate-800 hover:bg-slate-700',
        buttonIcon: 'text-orange-400',
        primary: 'bg-orange-700 hover:bg-orange-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-slate-800',
        progressFill: 'bg-orange-600',
        progressGlow: 'shadow-orange-900/50',
        arrow: 'border-t-orange-500',
    },
    rose: {
        bg: 'bg-slate-950',
        card: 'bg-slate-900',
        border: 'border-slate-800',
        text: 'text-slate-50',
        textSecondary: 'text-slate-200',
        textMuted: 'text-slate-500',
        accent: 'text-rose-400',
        accentHover: 'hover:text-rose-300',
        button: 'bg-slate-800 hover:bg-slate-700',
        buttonIcon: 'text-rose-400',
        primary: 'bg-rose-700 hover:bg-rose-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-slate-800',
        progressFill: 'bg-rose-600',
        progressGlow: 'shadow-rose-900/50',
        arrow: 'border-t-rose-500',
    },
    grey: {
        bg: 'bg-neutral-900',
        card: 'bg-neutral-800',
        border: 'border-neutral-700',
        text: 'text-neutral-100',
        textSecondary: 'text-neutral-200',
        textMuted: 'text-neutral-500',
        accent: 'text-neutral-400',
        accentHover: 'hover:text-neutral-300',
        button: 'bg-neutral-700 hover:bg-neutral-600',
        buttonIcon: 'text-neutral-300',
        primary: 'bg-neutral-600 hover:bg-neutral-500',
        primaryShadow: 'shadow-neutral-900/50',
        progressBg: 'bg-neutral-700',
        progressFill: 'bg-neutral-500',
        progressGlow: 'shadow-neutral-500/50',
        arrow: 'border-t-neutral-400',
    },
    black: {
        bg: 'bg-black',
        card: 'bg-zinc-950',
        border: 'border-zinc-900',
        text: 'text-zinc-100',
        textSecondary: 'text-zinc-200',
        textMuted: 'text-zinc-600',
        accent: 'text-zinc-400',
        accentHover: 'hover:text-zinc-300',
        button: 'bg-zinc-900 hover:bg-zinc-800',
        buttonIcon: 'text-zinc-400',
        primary: 'bg-zinc-700 hover:bg-zinc-600',
        primaryShadow: 'shadow-black/50',
        progressBg: 'bg-zinc-900',
        progressFill: 'bg-zinc-600',
        progressGlow: 'shadow-zinc-600/50',
        arrow: 'border-t-zinc-500',
    },
};
